<?xml version="1.0" encoding="UTF-8"?>
<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>CaetanoSoft</groupId>
	<artifactId>Library</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>21</maven.compiler.release>
		<exec.mainClass></exec.mainClass>
	</properties>
	<name>CaetanoSoft Java Library</name>
	<description>This is a Java library created by CaetanoSoft/José Caetano Silva
to help the development of Java applications.

Implements Java classes to ease the use of the Splash Screen, 
Printing, translation of the UI to portuguese and others.</description>
	<build>
    <finalName>${project.groupId}.${project.artifactId}-${project.version}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.4.1</version>
				<configuration>
					<finalName>${project.groupId}.${project.artifactId}-${project.version}</finalName>
					<archive>
						<index>true</index>
						<addMavenDescriptor>false</addMavenDescriptor>
						<manifestEntries>
							<Built-By></Built-By>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.15.0</version>
				<configuration>
					<release>${maven.compiler.release}</release>
					<encoding>${project.build.sourceEncoding}</encoding>
					<compilerArgs>
						<arg>-Xlint</arg>
					</compilerArgs>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>

